### ISSUE TITLE
Problem z formulami

### ISSUE THREAD

**Issue by joda49** [joda49/FP-projektna#1]
Pozdravljeni,
v repozitoriju imava datoteko z kodami. Pri definiranju zadnjih dveh funkcij (verjetnost in matrika_H) sva naletela na težavo. V prvi misliva, da nimava pravilnega indeksiranja (misliva, da dobiva rezultat za napačno vrstico). Pri drugi ma ne znava spisati kode za neskončno vrsto.

Lp,
Urban

**Comment by jaanos** [comment]
Mislim, da je glavni problem v tem, da imata matrike kot seznam seznamov, na katerem v funkciji `brisanje` uporabita metodo `pop` - tako se iz seznama odstrani element, kar pomeni, da se iz vhodne matrike pobriše vrstica. Pazita torej, da pred spreminjanjem matrik naredita ustrezne kopije.

Svetoval bi sicer, da za matrike uporabite kar Sageov razred `Matrix`. Tako bi lahko že generiranje matrik potekalo na tak način, npr.
```sage
def generiranje_matrik(m, n):
    d = m * n # število vrstic in stolpcev
    rd = range(d) # obseg indeksov
    matrika = Matrix(d, d) # matrika samih ničel
    for i in rd:
        for j in (i-1, i+1, i-n, i+1):
            if j in rd:
                matrika[i, j] = 1
    return matrika
```

Še lažje bo, če enostavno generirata ustrezni graf in vzameta njegovo matriko sosednosti:
```sage
def matrika_mreza(m, n):
    return graphs.Grid2dGraph(m, n).am()
```

Prehodno matriko lahko enostavno izračunata tako:
```sage
def prehodna_matrika_M(matrika):
    return Matrix([r/v for r, v in zip(matrika, sum(matrika))]) # vrstica / vsota vrstice
```

Za metodo `brisanje` lahko uporabita metodi `delete_columns` in `delete_rows`, ki vrneta matriko brez podanih stolpcev oziroma vrstic, pri čemer se originalna matrika ne spremeni:
```sage
def brisanje(j, matrika):
    return matrika.delete_columns([j]).delete_rows([j])
```

Pri izračunu vrednosti matrike *H* bo treba paziti, saj se privzame, da se indeksi pri brisanju vrstic in stolpcev ohranjajo - najlažje bo pred indeksiranjem ponovno dodati ustrezno vrstico. Da ne bo potrebno računati neskončnih vrst, bo bolje uporabiti spodnjo formulo z vsoto geometrijske vrste:
```sage
def dodajanje(j, matrika):
    return block_matrix([[matrika[:j, :j], 0, matrika[:j, j:]],
                         [0, Matrix(1, 1), 0],
                         [matrika[j:, :j], 0, matrika[j:, j:]]])

def matrika_H(i, j, matrika):
    IM = dodajanje(j, (identity_matrix(matrika.nrows()-1) - brisanje(j, matrika))^-2)
    return sum(IM[i, k] * matrika[k, j] for k in range(matrika.nrows()) if k != j)
```

Lahko pa enostavno poračunata celotno matriko *H* (kar bo bolj učinkovito, saj se isti inverz poračuna le enkrat za vsak stolpec):
```sage
def matrika_H(matrika):
    return Matrix([next(zip(*dodajanje(j, (identity_matrix(matrika.nrows()-1) - brisanje(j, matrika))^-2) * matrika[:, j]))
                   for j in range(matrika.ncols())]).transpose()
```

Mimogrede, svetujem, da v CoCalcu namesto *Sage worksheet* (končnica `.sagews`) delata z *Jupyter notebook* (končnica `.ipynb`) ter pod *Kernel* izbereta *SageMath 9.1* (po potrebi pa lahko tudi kak drug programski jezik). Take datoteke lahko potem odpirata tudi lokalno z orodjem Jupyter (če si namestita Sage lokalno, potem jih lahko tudi poganjata), pa tudi na GitHubu se bodo lepše prikazale.
