### ISSUE TITLE
Problem 2:

### ISSUE THREAD

**Issue by joda49** [joda49/FP-projektna#2]

**Comment by joda49** [comment]
Pozdravljeni,
popravila sva kode, ki ste jih izpostavili v prejšnjem problemu in spisala še ostale. Sedaj nama manjkajo samo še kode za generiranje 3D grafov in dreves. Problem imava samo pri funkcijah centralno_po_nsbc in centralnost_i.

Zanima naju tudi na katerih in kako velikih grafih mislite, da bi morala izvajati preizkuse?

Lp,
Urban

**Comment by joda49** [comment]
Vprašal bi vas še kako se uporabi funkcija am(), ki naredi matriko glede na graf (to ste nama predlagali pri prejšnjem problemu). Probal sem jo uporabiti na funkciji generator_binarnih_dreves vendar mi ne uspe.

**Comment by jaanos** [comment]
Kolikor vidim, je problem pri `centralno_po_nsbc` tukaj:
https://github.com/joda49/Random-walk-closeness-centrality/blob/ba0da0960a874273f2ff7e4dc0f798b4aab6a593/projekt.ipynb#L102-L104
Ni mi jasno, kaj sta poskusila tukaj doseči - kolikor vidim, indeksirata seznam z enim samim elementom (`[i]`) z rezultatom funkcije `nakjucni_sprehod_blizine_centralnosti`, ki vrača racionalno število. Slednjega bi sicer lahko z `int` pretvorila v celo število (zaokroženo proti 0), a mislim, da to ni to, kar sta želela.

Mimogrede, `nakjucni_sprehod_blizine_centralnosti` vsakič znova računa prehodno matriko, zato bo verjetno bolje, če jo poračunata vnaprej in to podasta kot argument funkcije.

Za `centralnost_i` pa lahko naredita tako:
```sage
def centralnost_i(i,matrika):  #centralno vozlišče
    s, = sum(oddaljenost_i(i,matrika))
    return 1/s
```
Kot sta sama videla, je rezultat seštevanja na matriki z enim stolpcem vektor z enim elementom - z zgornjim načinom se edini element zapiše v spremenljivko `s`, katere inverz lahko potem vrneta.

Kar se tiče `am`, je to metoda razreda `Graph` - lahko jo uporabita na objektih, ki jih vračajo metode objekta `graphs` (torej tudi na rezultatu funkcije `generator_binarnih_dreves`).
