### ISSUE TITLE
Problem 3D mreže

### ISSUE THREAD

**Issue by Lenart11** [joda49/FP-projektna#3]
V datoteki generiranje_matrik.ipynb sva naredila funkcijo za generiranje matrike za 3D mrežo (mat_3Dmreza(m,n,z). Če želiva iz dobljene matrike narisati graf z ukazom izris_grafa(matrika) nama funkcija vrne napako, ki je ne znava odpraviti.

Lp
Lenart

**Comment by jaanos** [comment]
Problem je v tem, da funkcija vrača matriko, ne grafa. Najprej poskrbita, da bo matrika simetrična (trenutno namreč ni) - na taki matriki lahko potem pokličeta `Graph`, da dobita graf.

Sicer pa lahko uporabita `graphs.GridGraph([m, n, z])`, da vama ni potrebno matrike sosednosti graditi na roko.
